Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "setup/php.sh"

  config.vm.post_up_message = "Your VM is ready to go! Web frontend at http://192.168.1.100"
  config.vm.network :private_network, ip: "192.168.1.100"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |v|
    v.name = "Notch"
    v.memory = 1024
  end
end